id: P221EF8EE
initial_creation_type: input
source_metadata:
  Title: Buddhist Himalaya Vol.1, No.2.
  Editor: Shakya, M. B.
  Publisher: Nagarjuna Institute of Exact Methods
  Place of Publication: Nepal
  Year: '1988'
  Āryānityatā sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:58:48.440424'
last_modified_at: '2022-03-08T15:58:48.440438'
